### ISSUE TITLE
The file is not a valid VSIX package

### ISSUE THREAD

**Issue by Hexzhe** [SpecFlowOSS/SpecFlow.VS#103]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

N/A

### Issue Description

Unable to install the extension on a fresh VS2022 from the extension website nor the extension manager.

> Install Failed
The install of '' was not successful for all the selected products.
For more information, click on the install log link at the bottom of the dialog.
The file is not a valid VSIX package.

`2022-09-29 11:43:58 - Microsoft VSIX Installer
2022-09-29 11:43:58 - -------------------------------------------
2022-09-29 11:43:58 - vsixinstaller.exe version:
2022-09-29 11:43:58 - 17.3.2092
2022-09-29 11:43:58 - -------------------------------------------
2022-09-29 11:43:58 - Command line parameters:
2022-09-29 11:43:58 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\li2h2q\Downloads\SpecFlow.VisualStudio.Package.vsix
2022-09-29 11:43:58 - -------------------------------------------
2022-09-29 11:43:58 - Microsoft VSIX Installer
2022-09-29 11:43:58 - -------------------------------------------
2022-09-29 11:43:58 - Initializing Install...
2022-09-29 11:43:58 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at MS.Internal.IO.Zip.ZipIOExtraField.ParseRecord(BinaryReader reader, ZipIOZip64ExtraFieldUsage zip64extraFieldUsage, UInt16 expectedExtraFieldSize)
   at MS.Internal.IO.Zip.ZipIOLocalFileHeader.ParseRecord(BinaryReader reader, Encoding encoding)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.ParseRecord(BinaryReader reader, String fileName, Int64 position, ZipIOCentralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.SeekableLoad(ZipIOBlockManager blockManager, String fileName)
   at MS.Internal.IO.Zip.ZipIOBlockManager.LoadLocalFileBlock(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFile(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\InstallableExtensionImpl.cs:line 83
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\InstallableExtensionImpl.cs:line 90
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\InstallableExtensionImpl.cs:line 40
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\ExtensionEngine.cs:line 738
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\ExtensionEngine.cs:line 728
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`

### Steps to Reproduce

Fresh install of VS2022 17.3.5
Install Specflow for VS2022 either from the extension manager or the website. Same result.

**Comment by SabotageAndi** [comment]
The Visual Studio Gallery checks the VSIX when we are uploading them.
Normally a corporate proxy is screwing around with the downloads when we see such problems.
