### ISSUE TITLE
Add .NET 7 support

### ISSUE THREAD

**Issue by LeftTwixWand** [SpecFlowOSS/SpecFlow.VS#115]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

This is the same issue as this: https://github.com/SpecFlowOSS/SpecFlow.VS/issues/5 but for .NET 7

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.RuntimeType.GetMethodBase(RuntimeModule scope, Int32 typeMetadataToken)
   at System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope, MetadataToken caCtorToken, ConstArray& blob)
   at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
   at System.Reflection.RuntimeAssembly.GetCustomAttributesData()
   at System.Reflection.Assembly.get_CustomAttributes()
   at SpecFlowConnector.ReflectionExecutor.Execute(DiscoveryOptions options, Func`3 testAssemblyFactory, ILogger _log, IAnalyticsContainer analytics) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\ReflectionExecutor.cs:line 14
   at SpecFlowConnector.Runner.ExecuteDiscovery(DiscoveryOptions options, Func`3 testAssemblyFactory) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line 44
   at SpecFlowConnector.Runner.<>c__DisplayClass4_0.<Run>b__0(ConnectorOptions options) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line 29
   at FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\NetExtensions\FunctionalExtensions.cs:line 5
   at SpecFlowConnector.Runner.Run(String[] args, Func`3 testAssemblyFactory) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line 26
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpecFlow.VisualStudio.Connectors.OutProcSpecFlowConnector.Deserialize(RunProcessResult result, Func`2 formatErrorMessage)
Warning: AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.

### Steps to Reproduce

Just set the test project version to .NET 7 and try to rebuild it

### Link to Repository Project

https://github.com/LeftTwixWand/Inventory

**Comment by momovuk** [comment]
Faced with the same issue, not possible to use .NET 7 with SpecFlow yet.

**Comment by njannink** [comment]
Any ETA or workaround for this issue?

**Comment by jrbye** [comment]
Hi. I am trying to decide if I need to downgrade the project I just worked to upgrade or if I can wait this out. Any new info?

**Comment by wozzo** [comment]
> Hi. I am trying to decide if I need to downgrade the project I just worked to upgrade or if I can wait this out. Any new info?

The Specflow build still works as expected. It's just the VS extension that is currently broken.
See [Generating Code Behind Files using MSBuild](https://specflow.org/using-specflow/generating-code-behind-files-using-msbuild/) for how to set up MS Build generation.

**Comment by jrbye** [comment]
> > Hi. I am trying to decide if I need to downgrade the project I just worked to upgrade or if I can wait this out. Any new info?
> 
> The Specflow build still works as expected. It's just the VS extension that is currently broken. See [Generating Code Behind Files using MSBuild](https://specflow.org/using-specflow/generating-code-behind-files-using-msbuild/) for how to set up MS Build generation.

I appreciate the response. I understand this is the case. I have my code behind files generating with the MsBuild.generation package. I have a lot of tests and I am struggling with the inability to navigate to the step definition from the feature file. That is why I was asking for an update.

**Comment by aelking** [comment]
Hi There,

Is there any update on this? While we get that it is just the extension that isn't working, we have found a work around, but would be good to get an eta on the full fix.

thanks.

**Comment by momovuk** [comment]
> Sadly not. Assembly loading issues are always a pain to find and debug. Give us some days please until we figure this out.

Any updates? When we could (in theory) expect the .NET 7 support?

**Comment by MonkeyTennis** [comment]
We have also hit this issue. Any update on when .NET 7 support for the Visual Studio extension can be expected to land?

**Comment by snickler** [comment]
Does anyone want to take a shot at adding the .NET 7 support? Now that my Arm64 PR was merged, I can give it a go since I actually have a need for it.

**Comment by aelking** [comment]
Looks like this has been release in https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.89

**Comment by jrbye** [comment]
I pulled the latest version of the Extension and it is working great! I am able to navigate to step definitions as expected. Thank you for the work on this Everyone.

**Comment by momovuk** [comment]
Same here. I took the latest extension version, and it works perfectly! Thanks everybody, I think this issue can be closed.

**Comment by LeftTwixWand** [comment]
Hey, it works fine for me to.
Want to thank everyone, who participated in dusscussion, and special cudos for @gasparnagy for quick response and fix of this issue. 💕
