### ISSUE TITLE
The project bindings (e.g. step definitions) could not be discovered.

### ISSUE THREAD

**Issue by gauravi555** [SpecFlowOSS/SpecFlow.VS#148]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
	  <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
  </configSections>
  <appSettings>
    <add key="seleniumBaseUrl" value="http://localhost:58909" />
  </appSettings>
  <specFlow>
    <unitTestProvider name="MSTest" />
    <plugins>
      <add name="Baseclass.Contrib.SpecFlow.Selenium.NUnit" path="..\packages\Baseclass.Contrib.SpecFlow.Selenium.NUnit.1.3.1\tools" /> 
    </plugins>
    <stepAssemblies>
      <stepAssembly assembly="Baseclass.Contrib.SpecFlow.Selenium.NUnit.Bindings" />
    </stepAssemblies>
  </specFlow>
  <autofac>
    <components>
      <component name="IE" type="OpenQA.Selenium.IE.InternetExplorerDriver, WebDriver" service="OpenQA.Selenium.IWebDriver, WebDriver" instance-scope="per-dependency">
      </component>
      <component name="Chrome" type="OpenQA.Selenium.Chrome.ChromeDriver, WebDriver" service="OpenQA.Selenium.IWebDriver, WebDriver" instance-scope="per-dependency">
      </component>
      <component name="Firefox" type="OpenQA.Selenium.Firefox.FirefoxDriver, WebDriver" service="OpenQA.Selenium.IWebDriver, WebDriver" instance-scope="per-dependency">
      </component>
      
    </components>
  </autofac>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="TechTalk.SpecFlow" publicKeyToken="0778194805d6db41" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.9.0.0" newVersion="3.9.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="BoDi" publicKeyToken="ff7cd5ea2744b496" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.5.0.0" newVersion="1.5.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Gherkin" publicKeyToken="86496cfa5b4a5851" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-19.0.3.0" newVersion="19.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

### Issue Description

I have created an Unit Test Project in visual studio the required references also added to the project level (NUnit, SpecFlow, BaseClass.Contrib.SpecFlow.Selenium.Nunit, SpecRun.Runner,Autofac, Autofac Configuration, SpecFlow.Assist.Dynamic etc.,).  after creating a feature file when i try to create step definition by right clicking, it is showing the popup saying all steps are define already 
 Note: it is only happening with the Unit test Project structure. 
<img width="374" alt="specflow_steps" src="https://github.com/SpecFlowOSS/SpecFlow.VS/assets/135152856/04450363-48b4-42c6-9ba2-c3c29d7473e1">

### Steps to Reproduce

1) Create a Unit Test Project
2) Create a feature folder and add the specflow feature file
3) Write the gherkin scenario for the created feature file
4) Install following packages (NUnit, SpecFlow, BaseClass.Contrib.SpecFlow.Selenium.Nunit, SpecRun.Runner,Autofac, Autofac Configuration, SpecFlow.Assist.Dynamic etc.,).
5) Create a step definition file and move it to the step definition folder.
6) save all and build the project.
7) right click on scenario, select Define steps.
8) and issue will arise (all steps are define already)

### Link to Repository Project

https://github.com/gauravi555/SpecFlowUnitTestProject.git

**Comment by jrbye** [comment]
I have the same situation. This is my log with some personal stuff scrubbed:

`Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: APIAutomation
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v8.0,SpecFlow:3.9.74
Warning: AndDiscoveryProviderSucceed: Error during binding discovery. 
Command executed:
  C:\Users\USER\source\repos\Automation\APIAutomation\bin\Debug\net8.0> C:\Program Files\dotnet\dotnet.exe exec c:\users\USER\appdata\local\microsoft\visualstudio\17.0_05a50cd2\extensions\4uipj3jo.qlj\Connectors\Generic-net7.0\specflow-vs.dll discovery C:\Users\USER\source\repos\BUNNAutomation\APIAutomation\bin\Debug\net8.0\APIAutomation.dll C:\Users\USER\source\repos\BUNNAutomation\APIAutomation\specflow.json
Exit code: 4
Message: 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.RuntimeType.GetMethodBase(RuntimeModule scope, Int32 typeMetadataToken)
   at System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope, MetadataToken caCtorToken, ConstArray& blob)
   at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at SpecFlowConnector.ReflectionExecutor.Execute(DiscoveryOptions options, Func`3 testAssemblyFactory, ILogger _log, IAnalyticsContainer analytics) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\ReflectionExecutor.cs:line 15
   at SpecFlowConnector.Runner.ExecuteDiscovery(DiscoveryOptions options, Func`3 testAssemblyFactory) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line 50
   at SpecFlowConnector.Runner.<>c__DisplayClass4_0.<Run>b__0(ConnectorOptions options) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line 30
   at FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\NetExtensions\FunctionalExtensions.cs:line 5
   at SpecFlowConnector.Runner.Run(String[] args, Func`3 testAssemblyFactory) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line 26
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpecFlow.VisualStudio.Connectors.OutProcSpecFlowConnector.Deserialize(RunProcessResult result, Func`2 formatErrorMessage)
Warning: AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.
Warning: AndDiscoveryProviderSucceed: Error during binding discovery. `

I get the same log for each project in the solution. I am not able to navigate to step definitions.

**Comment by rossoliverimdex** [comment]
Hi, I have this same issue. Same error. For me - I get this when my specflow project is targeting .net 8.0, but when I switch it back to 7.0 or 6.0 and it's fine. Unsure how to get my specflow to work properly with .NET 8. Unless I am missing something?

**Comment by jrbye** [comment]
There is a pre-release version of the extension that is available:
https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.93-net8

I downloaded and installed it and it is working.
