### ISSUE TITLE
Visual studio 2022 enterprise Specflow extension failing to load

### ISSUE THREAD

**Issue by veerNeti** [SpecFlowOSS/SpecFlow.VS#160]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

Error hash: 922178479
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81

### Issue Description

Extension on Visual studio is failing

### Steps to Reproduce

.

**Comment by Darth-Fx** [comment]
Same issue: Any fix or workaround available?

Error hash: 922178479
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81
