### ISSUE TITLE
SpecFlow Visual Studio Extension failing when loading any project in VS

### ISSUE THREAD

**Issue by jos-01-02** [SpecFlowOSS/SpecFlow.VS#161]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

Error hash: 922178479
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81

### Steps to Reproduce

-Install SpecFlow
-Open VS 2022
-Load any project

**Comment by ulluoink** [comment]
same for me

**Comment by MiroslawMarcin** [comment]
and same for me

**Comment by andrewvickersj2** [comment]
I have this too.

Machine:
Microsoft Visual Studio Professional 2022
Version 17.10.1
VisualStudio.17.Release/17.10.1+34928.147
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA608
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.10.338.1105
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2012   17.10.338.1105
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.10.338.1105
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.10.338.1105
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.10.0-3.24270.2+e8f775c1d8a73dee7ad02408712d714251e708ea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.5.3+7f0b0a9d18
PreEmptive Protection - Dotfuscator CE

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.60329.1 Commit Hash:15fce86a17f9f33e5bd7ca7ccb9b216aff149252
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.10.3.2427201+4f57d1de251e654812adde201c0265a8ca7ca31d
Provides languages services for ASP.NET Core Razor.

Silverlight for Visual Studio 2017, 2019, and 2022   1.0
Unofficial support for Silverlight projects in Visual Studio 2017, 2019, and 2022

SQL Server Data Tools   17.10.171.4
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30327.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.10.0-3.24270.2+e8f775c1d8a73dee7ad02408712d714251e708ea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.10.0-beta.24228.1+dd749058c91585e9b5dae62b0f8df892429ee28f
Microsoft Visual F# Tools

Visual Studio Extension for Reqnroll   1.0
Visual Studio extension for working with Reqnroll projects and Gherkin feature files.

Visual Studio Extension for SpecFlow   1.0
Visual Studio extension for working with SpecFlow projects and Gherkin feature files.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by linhdollyk67** [comment]
+ 1 same for me

**Comment by gopalverma** [comment]
same for me

**Comment by Jamie-Clayton** [comment]
Related VS 2022 issues https://github.com/SpecFlowOSS/SpecFlow.VS/issues/166
