### ISSUE TITLE
Error after installing Specflow extension in VS 2022 (17.10.5)

### ISSUE THREAD

**Issue by gopalverma** [SpecFlowOSS/SpecFlow.VS#171]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

**Error after installing Specflow extension in VS 2022 (17.10.5)**
Error hash: 922178479
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81

### Steps to Reproduce

Installed Specflow Extension > On creating a Specfow project, it threw the error pop up (attached log) > tried uninstall and reinstall but did not work
Logfile:
2024-07-28T00:27:53.092+01:00, Error@1, GetSafeLogger: Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "System.IO.Abstractions.IFileSystem" but found 2 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.GetSafeLogger(IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 47
2024-07-28T00:27:58.875+01:00, Verbose@1, LoadProjectSystem: Loading VsIdeScope...
2024-07-28T00:27:58.890+01:00, Error@1, ReportInitError: Initialization error : Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81
2024-07-28T00:28:11.085+01:00, Verbose@1, RegisterMenuCommands: RegenerateAllFeatureFileCodeBehindCommand registered
2024-07-28T00:33:19.736+01:00, Error@1, GetSafeLogger: Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "System.IO.Abstractions.IFileSystem" but found 2 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.GetSafeLogger(IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 47
2024-07-28T00:33:19.745+01:00, Verbose@1, LoadProjectSystem: Loading VsIdeScope...
2024-07-28T00:33:19.758+01:00, Error@1, ReportInitError: Initialization error : Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81
2024-07-28T00:33:24.689+01:00, Verbose@1, ReportError: Copy to clipboard: Error hash: 922178479
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81
2024-07-28T00:33:48.309+01:00, Verbose@1, RegisterMenuCommands: RegenerateAllFeatureFileCodeBehindCommand registered
2024-07-28T00:36:10.941+01:00, Error@1, GetSafeLogger: Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "System.IO.Abstractions.IFileSystem" but found 2 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.GetSafeLogger(IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 47
2024-07-28T00:36:10.948+01:00, Verbose@1, LoadProjectSystem: Loading VsIdeScope...
2024-07-28T00:36:10.956+01:00, Error@1, ReportInitError: Initialization error : Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81
2024-07-28T00:37:19.836+01:00, Verbose@1, RegisterMenuCommands: RegenerateAllFeatureFileCodeBehindCommand registered
2024-07-28T01:33:28.396+01:00, Error@1, GetSafeLogger: Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "System.IO.Abstractions.IFileSystem" but found 2 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.GetSafeLogger(IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 47
2024-07-28T01:33:28.405+01:00, Verbose@1, LoadProjectSystem: Loading VsIdeScope...
2024-07-28T01:33:28.418+01:00, Error@1, ReportInitError: Initialization error : Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 362
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 81

**Comment by Jamie-Clayton** [comment]
Relates to https://github.com/SpecFlowOSS/SpecFlow.VS/issues/166

**Comment by Jamie-Clayton** [comment]
Relates to https://github.com/SpecFlowOSS/SpecFlow.VS/issues/171

**Comment by Jamie-Clayton** [comment]
Installing https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.93-net8 does NOT fix the issue

**Comment by Jamie-Clayton** [comment]
Note the Visual Studio teams Feedback channel shows a [3 other extensions](https://developercommunity.visualstudio.com/VisualStudio?q=Microsoft.VisualStudio.Composition.CompositionFailedException&ftype=problem&stateGroup=active&sort=newest
) with issue in v17.10.x editions

I've also logged an issue with a parrallel fork in https://github.com/reqnroll/Reqnroll/issues/220 as they have the same behaviour.

**Comment by Jamie-Clayton** [comment]
Rolled back to v17.10.4, from v17.10.5 (VS Installer limits how far you go back)
Uninstalled previous editions of SpecFlow.
Downloaded [v2022 + .net 8.0 release](https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.93-net8) and installed a single extension.
Restarted VS2022 multiple times.
Everything working.

**Comment by apis3445** [comment]
I got the same error

**Comment by eklam** [comment]
This error is getting to the 6 month mark. Any updates on this?
