### ISSUE TITLE
InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled.

### ISSUE THREAD

**Issue by CoderAllan** [SpecFlowOSS/SpecFlow.VS#18]
I installed Visual Studio 2022 yesterday and installed SpecFlow for Visual Studio 2022. When i open my solution that contains  a UnitTest project with SpecFlow tests I cannot navigate (F12) to the definition of my SpecFlow steps.
This is the exception I get in the Visual Studio output:

Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: SpecFlowTesting
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: OnSettingsInitialized: Project settings initialized: .NETFramework,Version=v4.7.1,SpecFlow:3.9.8,x86
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\xxxxxx\xxxxxx\xxxxxx\xxxxxx\xxxxx\xxxxxx\xxxxxxxxxxxxxxxxxxxxxxx\SpecFlowProjectTesting\bin\Debug\net471> C:\USERS\xxxx\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_7DD401ED\EXTENSIONS\TDKTWEGU.DAF\Connectors\V1\specflow-vs-x86.exe discovery C:\Users\xxxxx\xxxxx\xxxxxxxxx\xxxxx\xxxxxx\xxxxxx\xxxxxxxxxxxxxxxxxxxx\SpecFlowProjectTesting\bin\Debug\net471\SpecFlowTesting.dll ""
Exit code: 4
Message: 
Error: Cannot create an instance of Microsoft.VisualStudio.TestTools.UnitTesting.TestContext because it is an abstract class.
Exception: System.MemberAccessException
StackTrace:

Server stack trace: 
   at System.Reflection.RuntimeConstructorInfo.CheckCanCreateInstance(Type declaringType, Boolean isVarArg)
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.Resolve[T](String name)
   at BoDi.ObjectContainer.Resolve[T]()
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunnerInstance()
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.V30.SpecFlowV30P220Discoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.RemotingBaseDiscoverer.Discover(String testAssemblyPath, String configFilePath)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.IRemotingSpecFlowDiscoverer.Discover(String testAssembly, String configFilePath)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process()
   at SpecFlow.VisualStudio.SpecFlowConnector.DiscoveryCommand.Execute(String[] commandArgs)
   at SpecFlow.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args)

Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.

**Comment by patiqs** [comment]
I am trying to reproduce. Can you send me the csproj of your test?

**Comment by patiqs** [comment]
Can you try to upgrade your specflow version?

**Comment by CoderAllan** [comment]
I'm sorry, I cannot provide you with the csproj file. Its company software.

I think I'm using the latest version of SpecFlow. This is what Visual Studio 2022 extensions tell me. No updates available.
![image](https://user-images.githubusercontent.com/11722431/141441189-ed38d116-6723-492c-85b1-51ad33c6d9dd.png)

**Comment by patiqs** [comment]
Please try to update the SpecFlow version in csproj. Not the VS extension.
You are using SpecFlow:3.9.8. Please try with 3.9.40 or 3.9.22

**Comment by CoderAllan** [comment]
I get the same error message after upgrading all SpecFlow NuGet packages to the latest:

`Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: SpecFlowTesting
Info: OnSettingsInitialized: Project settings initialized: .NETFramework,Version=v4.7.1,SpecFlow:3.9.40,x86
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\xxxxxx\xxxxxx\xxxxxx\xxxxxx\xxxxx\xxxxxx\xxxxxxxxxxxxxxxxxxxxxxx\SpecFlowProjectTesting\bin\Debug\net471> c:\users\xxxxx\appdata\local\microsoft\visualstudio\17.0_7dd401ed\extensions\tdktwegu.daf\Connectors\V1\specflow-vs-x86.exe discovery C:\Users\xxxxxx\xxxxxx\xxxxxx\xxxxxx\xxxxx\xxxxxx\xxxxxxxxxxxxxxxxxxxxxxx\SpecFlowProjectTesting\bin\Debug\net471\SpecFlowTesting.dll ""
Exit code: 4
Message: 
Error: Cannot create an instance of Microsoft.VisualStudio.TestTools.UnitTesting.TestContext because it is an abstract class.
Exception: System.MemberAccessException
StackTrace:

Server stack trace: 
   at System.Reflection.RuntimeConstructorInfo.CheckCanCreateInstance(Type declaringType, Boolean isVarArg)
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.<>c__DisplayClass71_0.<ResolveArguments>b__0(ParameterInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BoDi.ObjectContainer.ResolveArguments(IEnumerable`1 parameters, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.TypeRegistration.<>c__DisplayClass3_0.<ResolvePerContext>b__1()
   at BoDi.ObjectContainer.RegistrationWithStrategy.ExecuteWithLock(Object lockObject, Func`1 getter, Func`1 factory, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.TypeRegistration.ResolvePerContext(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.RegistrationWithStrategy.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.Resolve[T](String name)
   at BoDi.ObjectContainer.Resolve[T]()
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunnerInstance()
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.V30.SpecFlowV30P220Discoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.RemotingBaseDiscoverer.Discover(String testAssemblyPath, String configFilePath)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.IRemotingSpecFlowDiscoverer.Discover(String testAssembly, String configFilePath)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process()
   at SpecFlow.VisualStudio.SpecFlowConnector.DiscoveryCommand.Execute(String[] commandArgs)
   at SpecFlow.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args)

Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.
`

![image](https://user-images.githubusercontent.com/11722431/141453783-61a5d25e-9606-4d10-a772-61b6a1f7d6c6.png)

**Comment by patiqs** [comment]
I understand that you cannot share company sources. But somehow I need more info.
I am trying to reproduce this behavior here: https://github.com/SpecFlowOSS/Investigation
Can you try to add the minimum changes to reproduce the problem?

**Comment by patiqs** [comment]
Now we have the workaround. I will implement the fix in the next release

**Comment by lucasnoordzij** [comment]
Hi,
I am facing the same issues, can we share the workaround or should I raise a separate issue since it might be unique to each situation.

**Comment by Nickmullens** [comment]
Hi,

Can you share the workaround . I am facing the same issues.

**Comment by nawijesi** [comment]
same issue

**Comment by patiqs** [comment]
I released 2021.1.2 today. Can you validate?

**Comment by vadym-vereshchaka** [comment]
It worked fine for me yesterday but today I start getting the same error with the message: 
`The application to execute does not exist: 'C:\xxxxx\xxxxx\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_xxxxxx\EXTENSIONS\xxxx.xxxx\V3-net6.0\specflow-vs.dll'`
re-installing doesn't help. 
![image](https://user-images.githubusercontent.com/76945369/143228587-4260e7ea-ab68-4b73-8ee2-665bfae73243.png)

**Comment by CoderAllan** [comment]
The extension has been updated and Visual Studio restartet.
![image](https://user-images.githubusercontent.com/11722431/143228623-8cd22916-47b9-4ff4-995f-aa19f7d8f624.png)

I no longer get the massive stacktrace, but I get a warning and the navigation from the SpecFlow feature to the step definition does not work. I have testet both the minimal investigation solution and my large work solution with the same result.

The output:
`Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: 18_InvokeDiscovery_MicrosoftVisualStudioTestToolsUnitTestingTestContext
Info: OnSettingsInitialized: Project settings initialized: .NETFramework,Version=v4.7.1,SpecFlow:3.9.40
Warning: InvokeDiscovery: Error during binding discovery. Unable to find connector: C:\USERS\xxxxxx\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_7DD401ED\EXTENSIONS\SOUETNTU.B1M\V1\specflow-vs.exe
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.`

**Comment by barryhoughton** [comment]
I get a similar issue after updating the extension today - but I'm using .NET 5

`Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: Test.Specs
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v5.0,SpecFlow:3.9.40
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Repos\xxxxx\test\Test.Specs\bin\Debug\net5.0> C:\Program Files\dotnet\dotnet.exe exec c:\users\xxxxx\appdata\local\microsoft\visualstudio\17.0_51c0c241\extensions\qjrvrd1p.g53\V3-net6.0\specflow-vs.dll discovery C:\Repos\xxxxx\test\Test.Specs\bin\Debug\net5.0\Test.Specs.dll ""
Exit code: <not executed>
Message: 
The application to execute does not exist: 'c:\users\xxxxx\appdata\local\microsoft\visualstudio\17.0_51c0c241\extensions\qjrvrd1p.g53\V3-net6.0\specflow-vs.dll'
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.`

**Comment by MacShack** [comment]
I get a similar issue after de automatic update. As you can see I'm using VS 2022 in a .NET 6 project.

`
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: JClub.WorkflowService.Requirements
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v6.0,SpecFlow:3.9.40
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\xxx\source\repos\xxx\src\xxx\bin\Debug\net6.0> C:\Program Files\dotnet\dotnet.exe exec "C:\USERS\xxx\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_215CA4C9\EXTENSIONS\WHQIKDL3.NE2\V3-net6.0\specflow-vs.dll" discovery "C:\Users\xxx\source\repos\xxx\src\xxx\bin\Debug\net6.0\xxx.dll" "C:\Users\xxx\source\repos\xxx\src\xxx\specflow.json"
Exit code: <not executed>
Message: 
The application to execute does not exist: 'C:\USERS\xxx\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_215CA4C9\EXTENSIONS\WHQIKDL3.NE2\V3-net6.0\specflow-vs.dll'
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.`

**Comment by mcsmithcricut** [comment]
> It worked fine for me yesterday but today I start getting the same error with the message: `The application to execute does not exist: 'C:\xxxxx\xxxxx\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_xxxxxx\EXTENSIONS\xxxx.xxxx\V3-net6.0\specflow-vs.dll'` re-installing doesn't help. ![image](https://user-images.githubusercontent.com/76945369/143228587-4260e7ea-ab68-4b73-8ee2-665bfae73243.png) And path exists up to `\V3-net6.0\specflow-vs.dll` for some reason it is no `V3-net6.0` folder there

I'm having the same issue.

**Comment by maartencf** [comment]
I experience a similar issue on VS 2022. Below is the error log. The mentioned `V1` folder is also missing in my case.
```
Info: OnSettingsInitialized: Project settings initialized: .NETFramework,Version=v4.7.2,SpecFlow:3.1.82
Warning: InvokeDiscovery: Error during binding discovery. Unable to find connector: C:\USERS\<username>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_5F45EDBA\EXTENSIONS\UOTBFSLF.AIR\V1\specflow-vs.exe
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled.
```

**Comment by patiqs** [comment]
It seems there vas a packaging problem with the release. I just released 2021.1.4.55204 with the fix. Can you please verify?
https://marketplace.visualstudio.com/items?itemName=TechTalkSpecFlowTeam.SpecFlowForVisualStudio2022

**Comment by CoderAllan** [comment]
It is now working. I can navigate to step definitions as expected and i no longer get any errors in the output window.
Looks like the bug has been fixed.

Thank you!

**Comment by patiqs** [comment]
Thank you for the feeadback

**Comment by nawijesi** [comment]
still have the issue :( updated to latest extension

**Comment by maartencf** [comment]
It does work for me, so thanks a lot for the quick fix!

**Comment by rick3500** [comment]
This is my first attempt to build specflow using the 'Xamarin.UITest Cross-Platform Test Project' template and I am getting "The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled" message

It is actually a Warning and not an error.

Template used to initialize the project 'Xamarin.UITest Cross-Platform Test Project' w/FluidAssertions (6.2.0)
Microsoft.NET.Test.Sdk (17.0.0)
NUnit (3.13.2)
NUnit3TestAdapter (4.1.0)
Specflow.NUnit (3.9.40)
Specflow.Plus.LivingDocPlugin (3.9.57)
Visual Studio 2022 (64-bit) Current (Version 17.0.0
Xamarin - 17.0.0.336 (d17-0@29731f2)
Xamarin Designer - 17.0.0.182 (remotes/origin/d17-0@204898d)
Xamarin Templates - 17.0.17 (ie977b0)
Xamarin.Android.SDK - 12.1.0.5 (d17-0/6b0e6b2)
Xamarin.iOS and Xamarin.Mac SDK 15.0.0.18 (577ff6329)

**Comment by rick3500** [comment]
I just ran the vix @patiqs supplied now the warning has changed to No '<package>' elements found.
And that fixed the issue.
