### ISSUE TITLE
SpecFlow Visual Studio Extension detected an issue during initialization

### ISSUE THREAD

**Issue by vmiljkov** [SpecFlowOSS/SpecFlow.VS#51]
After updating the VS2022 to the latest, and also updating the SpecFlow extension to the latest, the extension is not working.
Here is the error:
Error hash: 1315591180
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope". ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Channels, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at SpecFlow.VisualStudio.Diagnostics.AsynchronousFileLogger..ctor(IFileSystem fileSystem, TraceLevel level)
   at SpecFlow.VisualStudio.Diagnostics.AsynchronousFileLogger.CreateInstance(IFileSystem fileSystem)
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScope..ctor(IServiceProvider serviceProvider, IVsSolutionEventListener solutionEventListener, IMonitoringService monitoringService, IDeveroomWindowManager windowManager, IFileSystem fileSystem) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScope.cs:line 34
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass63_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass52_3.<GetExports>b__5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass80_1`2.<GetExports>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 290
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 60

**Comment by dcdraper** [comment]
After launching VS 2022 today I also received the following:
Error hash: 1315591180
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope". ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Channels, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at SpecFlow.VisualStudio.Diagnostics.AsynchronousFileLogger..ctor(IFileSystem fileSystem, TraceLevel level)
   at SpecFlow.VisualStudio.Diagnostics.AsynchronousFileLogger.CreateInstance(IFileSystem fileSystem)
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScope..ctor(IServiceProvider serviceProvider, IVsSolutionEventListener solutionEventListener, IMonitoringService monitoringService, IDeveroomWindowManager windowManager, IFileSystem fileSystem) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScope.cs:line 34
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass63_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass52_3.<GetExports>b__5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass80_1`2.<GetExports>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 290
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 60

**Comment by dcdraper** [comment]
This now happens every time I try to open the solution; this is a blocker.

**Comment by MiloshR** [comment]
Hi, for me the same issue, on each project opening...

**Comment by dcdraper** [comment]
It looks like manually updating app.config to latest version of System.Threading.Tasks.Extensions MAY fix it...

Now:
![image](https://user-images.githubusercontent.com/35504583/147598702-e3565bc1-5611-4ea0-95ed-f0c8138b6173.png)

Was:
![image](https://user-images.githubusercontent.com/35504583/147598679-63568136-2b80-490b-b649-0bd0121d99cc.png)

**Comment by vadim-96** [comment]
The same problem(

**Comment by vmiljkov** [comment]
@vadim-96 , your temporary solution is working.
Thanks!

**Comment by Kocarik** [comment]
Blocker for me.

**Comment by fescobar** [comment]
I haven't tried the workaround, I can still use VS2019.
But this is critical for VS2020. I will be waiting for news soon.

**Comment by spashaa** [comment]
I am using VS2022 and this occurred after the specflow extension was updated automatically yesterday.

**Comment by patiqs** [comment]
I created a hotfix V2021.4.5 which includes the missing 'System.Threading.Channels.dll' to the package of the extension. Please check.

**Comment by patiqs** [comment]
I created a hotfix V2021.4.5 which includes the missing 'System.Threading.Channels.dll' to the package of the extension. Please check.

**Comment by spashaa** [comment]
Tried with the hotfix and it is working fine now. Thanks!

**Comment by fescobar** [comment]
@patiqs It's working. I will continue testing that version. Thank you so much!

**Comment by dcdraper** [comment]
@patiqs This works for me as well. Thank you!
