### ISSUE TITLE
I cant add a feature file

### ISSUE THREAD

**Issue by hmakda01** [SpecFlowOSS/SpecFlow.VS#54]
Error hash: 1315591180
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "SpecFlow.VisualStudio.ProjectSystem.VsIdeScope". ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Channels, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at SpecFlow.VisualStudio.Diagnostics.AsynchronousFileLogger..ctor(IFileSystem fileSystem, TraceLevel level)
   at SpecFlow.VisualStudio.Diagnostics.AsynchronousFileLogger.CreateInstance(IFileSystem fileSystem)
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScope..ctor(IServiceProvider serviceProvider, IVsSolutionEventListener solutionEventListener, IMonitoringService monitoringService, IDeveroomWindowManager windowManager, IFileSystem fileSystem) in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScope.cs:line 34
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass63_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass52_3.<GetExports>b__5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass80_1`2.<GetExports>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at SpecFlow.VisualStudio.VsUtils.ResolveMefDependency[T](IServiceProvider serviceProvider) in D:\a\1\s\SpecFlow.VisualStudio.Package\VsUtils.cs:line 290
   at SpecFlow.VisualStudio.ProjectSystem.VsIdeScopeLoader.LoadProjectSystem() in D:\a\1\s\SpecFlow.VisualStudio.Package\ProjectSystem\VsIdeScopeLoader.cs:line 60

**Comment by patiqs** [comment]
I created a hotfix V2021.4.5 which includes the missing 'System.Threading.Channels.dll' to the package of the extension. Please check.

**Comment by alimogithub** [comment]
@hmakda01 please let us know if the latest release has resolved the issue.
Cheers
