### ISSUE TITLE
Warning: AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 

### ISSUE THREAD

**Issue by genuineroshan** [SpecFlowOSS/SpecFlow.VS#58]
```
Exit code: 3
Message: 
Exception in:SpecFlow.VisualStudio.SpecFlowConnector.Discovery.SpecFlowV30Discoverer
Error: Value cannot be null.
Parameter name: key
Exception: System.ArgumentNullException
StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.FindAttributeConstructorArg(ParameterInfo parameterInfo, Dictionary`2 namedAttributeValues)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.CreateAttribute(Attribute attribute)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.CreateBindingSourceMethod(MethodInfo methodDefinition)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.BuildBindingsFromType(Type type)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.BuildBindingsFromAssembly(Assembly assembly)
   at TechTalk.SpecFlow.TestRunnerManager.BuildBindingRegistry(IEnumerable`1 bindingAssemblies)
   at TechTalk.SpecFlow.TestRunnerManager.InitializeBindingRegistry(ITestRunner testRunner)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.SpecFlowVLatestDiscoverer.ResolveBindingRegistry(Assembly testAssembly, Object globalContainer) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V1\Discovery\SpecFlowVLatestDiscoverer.cs:line 49
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\Discovery\BaseDiscoverer.cs:line 52
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.RemotingBaseDiscoverer.Discover(String testAssemblyPath, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V1\Discovery\RemotingBaseDiscoverer.cs:line 12
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V1\Discovery\DiscoveryProcessor.cs:line 16
   at SpecFlow.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\ConsoleRunner.cs:line 31

Warning: AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
```

**Comment by genuineroshan** [comment]
.NETFramework,Version=v4.8
SpecFlow:3.0.225,x64

**Comment by patiqs** [comment]
Can you try to upgrade specflow to 3.9.40 and check if it works?

**Comment by patiqs** [comment]
I plan to fix this in the next release. Please help me to reproduce this issue locally on my laptop.
The best would be if you can create and share a repo where the issue exists.
Or I can give you write access to our [investigation repo](https://github.com/SpecFlowOSS/Investigation), where you can commit a sample.
If this doesn't work, then I need the csproj content of your test project

**Comment by gasparnagy** [comment]
@genuineroshan We have tried to create a repro for this with @patiqs, but could not. 

It might also be a transient issue that goes away if you do a full rebuild and reopen Visual Studio. 

I close this issue now, but if you still experience the problem and can make a simple project that shows the issue, please reopen the issue and we are happy to fix it.
