### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by cliveontoast** [SpecFlowOSS/SpecFlow.VS#6]
Awesome output info in the specflow pane in the output tab. well done.

When I initially loaded my project after going through the specflow wizard, this popped up.

```
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: my.project.Specs
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v5.0,SpecFlow:3.9.22
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\folder.to.project.Specs\bin\Debug\net5.0> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\myname\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_C8A3E5A9\EXTENSIONS\LL2KURGV.3QJ\Connectors\V3-net5.0\specflow-vs.dll discovery C:\folder.to.project.Specs\bin\Debug\net5.0\my.project.Specs.dll ""
Exit code: 4
Message: 
Error: Exception has been thrown by the target of an invocation. -> Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Exception: System.Reflection.TargetInvocationException->System.Reflection.ReflectionTypeLoadException
StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.BuildBindingsFromAssembly(Assembly assembly)
   at TechTalk.SpecFlow.TestRunnerManager.BuildBindingRegistry(IEnumerable`1 bindingAssemblies)
   at TechTalk.SpecFlow.TestRunnerManager.InitializeBindingRegistry(ITestRunner testRunner)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId)
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.SpecFlowV3BaseDiscoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V3\Discovery\SpecFlowV3BaseDiscoverer.cs:line 28
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\Discovery\BaseDiscoverer.cs:line 31
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\Discovery\BaseDiscoverer.cs:line 21
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.VersionSelectorDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V3\Discovery\VersionSelectorDiscoverer.cs:line 25
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SpecFlow.VisualStudio.SpecFlowConnector.ReflectionExtensions.ReflectionCallMethod[T](Object obj, String methodName, Type[] parameterTypes, Object[] args) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\ReflectionExtensions.cs:line 30
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.ReflectionSpecFlowDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V3\Discovery\ReflectionSpecFlowDiscoverer.cs:line 21
   at SpecFlow.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.V2\Discovery\DiscoveryProcessor.cs:line 26
   at SpecFlow.VisualStudio.SpecFlowConnector.DiscoveryCommand.Execute(String[] commandArgs) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\DiscoveryCommand.cs:line 17
   at SpecFlow.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector\ConsoleRunner.cs:line 23

Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.

```

**Comment by cliveontoast** [comment]
I'm speculating, but does that cause this warning?

![image](https://user-images.githubusercontent.com/35511400/135401473-afd0d317-e3d3-4b79-9556-7326fbb1e603.png)

**Comment by patiqs** [comment]
This warning is the symptom not the cause.
How does your specflow related package references look like in your test .csproj?

**Comment by cliveontoast** [comment]
I remoted in.

This is what is directly in the test.csproj file

```
  <ItemGroup>
    <PackageReference Include="AdCodicem.SpecFlow.MicrosoftDependencyInjection" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="3.1.18" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="Shouldly" Version="3.0.2" />
    <PackageReference Include="SpecFlow.MsTest" Version="3.9.22" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.5" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.5" />
    
  </ItemGroup>
```

this is in the .csproj that the specs are testing

```
  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="3.6.3" />
    <PackageReference Include="Humanizer.Core" Version="2.11.10" />    
    <PackageReference Include="EFCore.DbContextFactory" Version="2.0.0" />
    <PackageReference Include="FluentValidation" Version="9.5.1" />
    <PackageReference Include="LazyCache.AspNetCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>    
    <PackageReference Include="Pastel" Version="2.1.0" />    
    <PackageReference Include="RestSharp" Version="106.12.0" />    
    <PackageReference Include="System.Collections" Version="4.3.0" />
  </ItemGroup>
```

Further down the project references

```
  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.2.5" />
    <PackageReference Include="EPPlus" Version="5.7.3" />
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.6.0" />
    <PackageReference Include="Hangfire.ASPNETCore" Version="1.7.24" />
    <PackageReference Include="Hangfire.Console" Version="1.4.2" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.7.24" />
    <PackageReference Include="LazyCache" Version="2.1.3" />  
    <PackageReference Include="NetCore.Jwt" Version="1.0.2" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.1.5" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="4.7.0" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="2.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.12" />
    <PackageReference Include="System.IO.Packaging" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="5.0.0" />
  </ItemGroup>
```

Further down the project references

```
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="9.5.1" />
    <PackageReference Include="Humanizer.Core" Version="2.11.10" />
    <PackageReference Include="Dapper" Version="2.0.90" />
    <PackageReference Include="Fastmember" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.9" />    
    <PackageReference Include="MoreLinq" Version="3.3.2" />
  </ItemGroup>
```

**Comment by cliveontoast** [comment]
![image](https://user-images.githubusercontent.com/35511400/135466910-cb09b7a7-893b-40f8-be36-db50a68e4216.png)

**Comment by patiqs** [comment]
Do you have the latest version of the extension? We faced similar issue in v2021.0.185. We fixed in v2021.0.187

**Comment by patiqs** [comment]
v2021.0.191 Is released today. Can you check with it?
